version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      testing:
        patterns:
          - "coverlet.*"
          - "Microsoft.NET.Test.Sdk"
          - "Microsoft.Testing.*"
          - "xunit.*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
    cooldown:
      default-days: 7
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
